name: prComment
on: [pull_request]

jobs:
  examples-pr-comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: npm run deployPRComment
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
